# Generated by Django 4.0.6 on 2023-03-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal_sale', '0002_category2_rename_category_category1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category1',
            name='image',
            field=models.ImageField(upload_to='image/category1/'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='image',
            field=models.ImageField(upload_to='image/category2/'),
        ),
    ]
