# Generated by Django 4.0.6 on 2023-03-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Animal_sale', '0003_alter_category1_image_alter_category2_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=500, unique=True)),
                ('image', models.ImageField(upload_to='images/quiz/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animal_sale.category1')),
            ],
        ),
        migrations.CreateModel(
            name='Species1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=500, unique=True)),
                ('image', models.ImageField(upload_to='images/quiz/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animal_sale.category1')),
            ],
        ),
    ]
