# Generated by Django 4.0.6 on 2023-03-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Animal_sale', '0004_species2_species1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species2',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animal_sale.category2'),
        ),
    ]
