# Generated by Django 4.0.2 on 2023-03-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal_sale', '0007_species2_species1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='category',
            new_name='category2',
        ),
    ]
