# Generated by Django 4.0.2 on 2023-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal_sale', '0008_rename_category_thread_category2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=70)),
                ('MiddelName', models.CharField(max_length=70)),
                ('LastName', models.CharField(max_length=70)),
                ('Password', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=70)),
                ('Phone', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, unique=True)),
            ],
        ),
    ]
