# Generated by Django 4.0.2 on 2023-03-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal_sale', '0010_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='BuyWithin',
            field=models.CharField(choices=[('1', '15 day'), ('2', '30 day'), ('3', '>30 day')], default='1', max_length=20),
        ),
    ]
